INSERT INTO `kiosk`.`store` (`store_id`, `store_name`, `store_open_time`, `store_close_time`, `user_id`) VALUES ('1', '스타벅스', '8', '22', 'admin');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('1', '콜드 브루 커피', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('2', '브루드 커피', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('3', '에스프레소', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('4', '프라푸치노', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('5', '블렌디드', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('6', '티', '999', '1');
INSERT INTO `kiosk`.`category` (`category_id`, `category_name`, `category_priority`, `store_id`) VALUES ('7', '주스', '999', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('1', '리저브 나이트로', '8000','1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('2', '나이트로 바닐라 크림', '6500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('3', '나이트로 콜드 브루', '6500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('4', '돌체 콜드 브루', '7000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('5', '리저브 콜드 브루', '8000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('6', '민트 콜드 브루', '6500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('7', '바닐라 크림 콜드 브루', '6500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('8', '시그니처 더 블랙 콜드 브루', '7000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('9', '오트 콜드 브루', '7000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('10', '제주 비자림 콜드 브루', '7500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('11', '제주 시트러스 허니 콜드 브루', '7500', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('12', '콜드 브루', '6000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('13', '콜드 브루 몰트', '7000', '1', '1', '1');
INSERT INTO `kiosk`.`menu` (`menu_id`, `menu_name`, `menu_price`, `menu_state`, `category_id`, `store_id`) VALUES ('14', '콜드 브루 플로트', '7000', '1', '1', '1');
